pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'mkdir /.cache RUN chmod -R 777 /.cache ...'
                    sh 'go test -v ./...'
                }

            }
        }
    }
}
